[[Backends]]
name = "LSF"
kind = "Generic"
submit = """
    bsub \
        -q ~{lsf_queue} \
        -n ~{cpu} \
        -cwd ~{cwd} \
        -o ~{cwd}/stdout.lsf \
        -e ~{cwd}/stderr.lsf \
        -R "rusage[mem=~{memory_mb}] span[hosts=~{hosts}]" \
        ~{script}
"""
default-ram = 3000
runtime_attrs = { lsf_queue = "compbio", hosts = 1, cpu = 1 }
job_id_regex = "Job <(\\d+)>.*"
monitor = "check-job-alive ~{job_id}"
monitor_frequency = 5
kill = "bkill ~{job_id}"
